In [319]:
import pandas as pd
import json
import os

In [320]:
x = []


# for file in os.listdir("./etis/"):
#   filepath = os.path.join("./etis/", file)
#   with open(filepath, 'r') as file:
#     data = json.load(file)
#     x.append(data)


filepath = '../etis/4868.json'


with open(filepath, 'r') as file:
     data = json.load(file)
     x.append(data)

In [321]:
dados_normalizados = pd.json_normalize(x)
dados_normalizados.head()

,codigo,nome,descricao,fonte,tipoValor,tags,secretarias,autarquias,metas,eixos,valores,periodicidade.codigo,periodicidade.descricao
0,4868,População total do município,População total do município - Cidades Sustent...,IBGE,I,"[{'codigo': 1, 'descricao': 'Santos Acolhedora'}]","[{'codigo': 4681, 'dado_codigo': 4868, 'sigla'...",[],"[{'codigo': 13, 'numero': 12, 'titulo': 'Consu...","[{'codigo': 12, 'descricao': 'Consumo Responsá...","[{'codigo': 1531, 'data': '2013-12-31 00:00:00...",6,Anual

In [322]:
print(len((dados_normalizados['autarquias'][0])))

0

In [323]:
orgao = "autarquias" if len((dados_normalizados['autarquias'][0])) > 0 else "secretarias"

#dados_normalizados['autarquias'][0][0]['codigo']
dados_normalizados['id_orgao'] = dados_normalizados[orgao][0][0]['codigo']
dados_normalizados['sigla_orgao'] = dados_normalizados[orgao][0][0]['sigla']
dados_normalizados.drop(columns=['autarquias','secretarias'], inplace=True)
dados_normalizados['tipo_orgao'] = orgao
dados_normalizados

,codigo,nome,descricao,fonte,tipoValor,tags,metas,eixos,valores,periodicidade.codigo,periodicidade.descricao,id_orgao,sigla_orgao,tipo_orgao
0,4868,População total do município,População total do município - Cidades Sustent...,IBGE,I,"[{'codigo': 1, 'descricao': 'Santos Acolhedora'}]","[{'codigo': 13, 'numero': 12, 'titulo': 'Consu...","[{'codigo': 12, 'descricao': 'Consumo Responsá...","[{'codigo': 1531, 'data': '2013-12-31 00:00:00...",6,Anual,4681,SEFIN,secretarias

In [324]:
dados_normalizados.drop(columns=['tags', 'metas', 'eixos', 'periodicidade.codigo', 'periodicidade.descricao'], inplace=True)

In [325]:
dados_normalizados = dados_normalizados.explode('valores')

In [326]:
dados_normalizados['valores']

0    {'codigo': 1531, 'data': '2013-12-31 00:00:00'...
0    {'codigo': 1532, 'data': '2014-12-31 00:00:00'...
0    {'codigo': 1533, 'data': '2017-12-31 00:00:00'...
0    {'codigo': 1534, 'data': '2015-12-31 00:00:00'...
0    {'codigo': 1535, 'data': '2016-12-31 00:00:00'...
0    {'codigo': 3693, 'data': '2018-12-31 00:00:00'...
0    {'codigo': 4143, 'data': '2019-12-31 00:00:00'...
0    {'codigo': 5052, 'data': '2020-12-31 00:00:00'...
0    {'codigo': 6021, 'data': '2021-12-30 00:00:00'...
0    {'codigo': 6897, 'data': '2022-12-31 00:00:00'...
0    {'codigo': 7536, 'data': '2023-12-31 00:00:00'...
Name: valores, dtype: object

In [327]:
dados_normalizados['valores.valor'] = dados_normalizados['valores'].apply(lambda x: x['valor'])
dados_normalizados['valores.codigo'] = dados_normalizados['valores'].apply(lambda x: x['codigo'])
dados_normalizados['valores.data'] = dados_normalizados['valores'].apply(lambda x: x['data'])
#dados_normalizados['valores.descricao'] = dados_normalizados['descricao'].apply(lambda x: x['descricao'])

In [328]:
dados_normalizados

,codigo,nome,descricao,fonte,tipoValor,valores,id_orgao,sigla_orgao,tipo_orgao,valores.valor,valores.codigo,valores.data
0,4868,População total do município,População total do município - Cidades Sustent...,IBGE,I,"{'codigo': 1531, 'data': '2013-12-31 00:00:00'...",4681,SEFIN,secretarias,433153.00,1531,2013-12-31 00:00:00
0,4868,População total do município,População total do município - Cidades Sustent...,IBGE,I,"{'codigo': 1532, 'data': '2014-12-31 00:00:00'...",4681,SEFIN,secretarias,433565.00,1532,2014-12-31 00:00:00
0,4868,População total do município,População total do município - Cidades Sustent...,IBGE,I,"{'codigo': 1533, 'data': '2017-12-31 00:00:00'...",4681,SEFIN,secretarias,434742.00,1533,2017-12-31 00:00:00
0,4868,População total do município,População total do município - Cidades Sustent...,IBGE,I,"{'codigo': 1534, 'data': '2015-12-31 00:00:00'...",4681,SEFIN,secretarias,433966.00,1534,2015-12-31 00:00:00
0,4868,População total do município,População total do município - Cidades Sustent...,IBGE,I,"{'codigo': 1535, 'data': '2016-12-31 00:00:00'...",4681,SEFIN,secretarias,434359.00,1535,2016-12-31 00:00:00
0,4868,População total do município,População total do município - Cidades Sustent...,IBGE,I,"{'codigo': 3693, 'data': '2018-12-31 00:00:00'...",4681,SEFIN,secretarias,432957.00,3693,2018-12-31 00:00:00
0,4868,População total do município,População total do município - Cidades Sustent...,IBGE,I,"{'codigo': 4143, 'data': '2019-12-31 00:00:00'...",4681,SEFIN,secretarias,433311.00,4143,2019-12-31 00:00:00
0,4868,População total do município,População total do município - Cidades Sustent...,IBGE,I,"{'codigo': 5052, 'data': '2020-12-31 00:00:00'...",4681,SEFIN,secretarias,433656.00,5052,2020-12-31 00:00:00
0,4868,População total do município,População total do município - Cidades Sustent...,IBGE,I,"{'codigo': 6021, 'data': '2021-12-30 00:00:00'...",4681,SEFIN,secretarias,433991.00,6021,2021-12-30 00:00:00
0,4868,População total do município,População total do município - Cidades Sustent...,IBGE,I,"{'codigo': 6897, 'data': '2022-12-31 00:00:00'...",4681,SEFIN,secretarias,418608.00,6897,2022-12-31 00:00:00
0,4868,População total do município,População total do município - Cidades Sustent...,IBGE,I,"{'codigo': 7536, 'data': '2023-12-31 00:00:00'...",4681,SEFIN,secretarias,418608.00,7536,2023-12-31 00:00:00

In [329]:
dados_normalizados.drop(columns='valores', inplace=True)
dados_normalizados

,codigo,nome,descricao,fonte,tipoValor,id_orgao,sigla_orgao,tipo_orgao,valores.valor,valores.codigo,valores.data
0,4868,População total do município,População total do município - Cidades Sustent...,IBGE,I,4681,SEFIN,secretarias,433153.00,1531,2013-12-31 00:00:00
0,4868,População total do município,População total do município - Cidades Sustent...,IBGE,I,4681,SEFIN,secretarias,433565.00,1532,2014-12-31 00:00:00
0,4868,População total do município,População total do município - Cidades Sustent...,IBGE,I,4681,SEFIN,secretarias,434742.00,1533,2017-12-31 00:00:00
0,4868,População total do município,População total do município - Cidades Sustent...,IBGE,I,4681,SEFIN,secretarias,433966.00,1534,2015-12-31 00:00:00
0,4868,População total do município,População total do município - Cidades Sustent...,IBGE,I,4681,SEFIN,secretarias,434359.00,1535,2016-12-31 00:00:00
0,4868,População total do município,População total do município - Cidades Sustent...,IBGE,I,4681,SEFIN,secretarias,432957.00,3693,2018-12-31 00:00:00
0,4868,População total do município,População total do município - Cidades Sustent...,IBGE,I,4681,SEFIN,secretarias,433311.00,4143,2019-12-31 00:00:00
0,4868,População total do município,População total do município - Cidades Sustent...,IBGE,I,4681,SEFIN,secretarias,433656.00,5052,2020-12-31 00:00:00
0,4868,População total do município,População total do município - Cidades Sustent...,IBGE,I,4681,SEFIN,secretarias,433991.00,6021,2021-12-30 00:00:00
0,4868,População total do município,População total do município - Cidades Sustent...,IBGE,I,4681,SEFIN,secretarias,418608.00,6897,2022-12-31 00:00:00
0,4868,População total do município,População total do município - Cidades Sustent...,IBGE,I,4681,SEFIN,secretarias,418608.00,7536,2023-12-31 00:00:00